--Q1 What is the total number of units sold per product SKU?

SELECT PRODUCTID, SUM(INVENTORYQUANTITY) AS TOTAL_UNIT_SOLD
FROM SALES
GROUP BY PRODUCTID;

--Q2 Which product category had the highest sales volume last month?

SELECT PRODUCTCATEGORY, SUM(INVENTORYQUANTITY) AS SALES_VOLUME
FROM SALES
JOIN PRODUCT ON PRODUCT.PRODUCTID = SALES.PRODUCTID
WHERE SALES_YEAR = '2021' AND SALES_MONTH = '11'
GROUP BY PRODUCTCATEGORY
ORDER BY SALES_VOLUME DESC;

--Q3 How does the inflation rate correlate with sales volume for a specific month?

SELECT SALES_MONTH, SALES_YEAR,ROUND(AVG(INFLATIONRATE),4) AS AVG_INFLATION,SUM(INVENTORYQUANTITY) AS SALES_VOLUME
FROM SALES
JOIN FACTORS ON FACTORS.SALESDATE = SALES.SALESDATE
GROUP BY SALES_YEAR,SALES_MONTH;

--Q4 What is the correlation between the inflation rate and sales quantity for all products combined on a
--monthly basis over the last year?

SELECT SALES_MONTH,SALES_YEAR,ROUND (AVG(INFLATIONRATE),4) AS AVG_INFLATION, SUM(INVENTORYQUANTITY)AS SALE_VOLUME
FROM SALES
JOIN FACTORS ON FACTORS.SALESDATE = SALES.SALESDATE
WHERE SALES.SALESDATE >= (CURRENT_DATE - INTERVAL '1 YEAR')
GROUP BY SALES_YEAR,SALES_MONTH;

--Q5 Did promotions significantly impact the sales quantity of products? 

SELECT PRODUCT.PRODUCTCATEGORY, ROUND (AVG(SALES.INVENTORYQUANTITY),2) AS AVG_SALES_WITH_PROMO, PRODUCT.PROMOTIONS
FROM SALES
JOIN PRODUCT ON PRODUCT.PRODUCTID = SALES.PRODUCTID
WHERE PRODUCT.PROMOTIONS = 'YES'
GROUP BY PRODUCT.PRODUCTCATEGORY, PRODUCT.PROMOTIONS

UNION ALL 

SELECT PRODUCT.PRODUCTCATEGORY, ROUND (AVG(SALES.INVENTORYQUANTITY),2) AS AVG_SALES_WIHOUT_PROMOTIONS, PRODUCT.PROMOTIONS
FROM SALES
JOIN PRODUCT ON PRODUCT.PRODUCTID = SALES.PRODUCTID
WHERE PRODUCT.PROMOTIONS = 'NO'
GROUP BY PRODUCT.PRODUCTCATEGORY, PRODUCT.PROMOTIONS;


--Q6 What is the average sales quantity per product category?

SELECT PRODUCT.PRODUCTCATEGORY, ROUND (AVG (SALES.INVENTORYQUANTITY)) AS AVG_SALES_QTY
FROM SALES
JOIN PRODUCT ON SALES.PRODUCTID = PRODUCT.PRODUCTID
GROUP BY PRODUCT.PRODUCTCATEGORY;


--Q7 How does the GDP affect the total sales volume?

SELECT S.SALES_YEAR, SUM(F.GDP)AS TOTAL_GDP, SUM(S.INVENTORYQUANTITY)AS TOTAL_SALES
FROM SALES S
JOIN FACTORS F ON F.SALESDATE = S.SALESDATE
GROUP BY S.SALES_YEAR
ORDER BY TOTAL_SALES DESC;

--Q8 What are the top 10 best-selling product SKUs?

SELECT PRODUCTID, SUM(INVENTORYQUANTITY) AS SALES_VOLUME
FROM SALES 
GROUP BY PRODUCTID
ORDER BY SALES_VOLUME DESC
LIMIT 10;

--Q8 How do seasonal factors influence sales quantities for different product categories?

SELECT P.PRODUCTCATEGORY, SUM(S.INVENTORYQUANTITY) AS TOTAL_SALES, ROUND (AVG(F.SEASONALFACTOR),4) AS AVG_SFACTOR
FROM SALES S
JOIN PRODUCT P ON P.PRODUCTID = S.PRODUCTID
JOIN FACTORS F ON S.SALESDATE = F.SALESDATE
GROUP BY P.PRODUCTCATEGORY;


--Q9 What is the average sales quantity per product category, and how many products within each
--category were part of a promotion?

SELECT P.PRODUCTCATEGORY, ROUND (AVG(S.INVENTORYQUANTITY),4) AS AVG_SALE_QTY, 
COUNT(CASE
	WHEN P.PROMOTIONS = 'YES' THEN 1 END) AS PROMOTION_COUNT
FROM SALES S 
JOIN PRODUCT P ON P.PRODUCTID = S.PRODUCTID
GROUP BY P.PRODUCTCATEGORY
ORDER BY AVG_SALE_QTY;



SELECT PRODUCTID
FROM PRODUCT
WHERE PROMOTIONS ='YES';












SELECT * FROM FACTORS;
SELECT * FROM PRODUCT;
SELECT * FROM SALES;